import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'hi', 'mr', 'ur', 'pa', 'ta', 'te', 'gu', 'bn', 'kn', 'ml'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? hiText = '',
    String? mrText = '',
    String? urText = '',
    String? paText = '',
    String? taText = '',
    String? teText = '',
    String? guText = '',
    String? bnText = '',
    String? knText = '',
    String? mlText = '',
  }) =>
      [
        enText,
        hiText,
        mrText,
        urText,
        paText,
        taText,
        teText,
        guText,
        bnText,
        knText,
        mlText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // SplashScreen
  {
    'hfaboh17': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Auth2
  {
    'yds8qba4': {
      'en': 'MIND MENDER',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'myap9p3n': {
      'en': 'Sign In',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'e6ig7g4k': {
      'en': 'Sign Up',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    't845ozms': {
      'en': 'Let\'s get started by filling out the form below.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'c6rj59wf': {
      'en': 'Email',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k8hh411t': {
      'en': 'Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'so05o2rm': {
      'en': 'Sign In',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '90vsevd4': {
      'en': 'Forgot Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lmpxh6qb': {
      'en': 'Or sign up with',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8jfzog81': {
      'en': 'Continue with Google',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tqtvcilq': {
      'en': 'Continue with fackbook',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0eic85ih': {
      'en': 'Continue with Apple',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qy3f37r7': {
      'en': 'Email',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1c9yt0d9': {
      'en': 'Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ihl4c54r': {
      'en': 'Confirm Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qzo1wxiz': {
      'en': 'Create Account',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rsxxn5cl': {
      'en': 'Or sign up with',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'upmy0lxn': {
      'en': 'Continue with Google',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2ga6tzzr': {
      'en': 'Continue with Apple',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1wl81u2i': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // forgotpassword
  {
    'ev4rphbm': {
      'en': 'Back',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'djgghr3t': {
      'en': 'Forgot Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dixqdwyl': {
      'en':
          'We will send you an email with a link to reset your password, please enter the email associated with your account below.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j2zxbz2a': {
      'en': 'Your email address...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'sbfawkg9': {
      'en': 'Enter your email...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ufgn0z7v': {
      'en': 'Send Link',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0j2oxf3g': {
      'en': 'Back',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '67b3u9p6': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // home
  {
    'lf86aaea': {
      'en': 'Find some wonderful little cabins below.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wrk13kja': {
      'en': 'Search...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wd0rr7ac': {
      'en': 'What is Mental Health?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ujclrxvg': {
      'en':
          'Mental health is a state of emotional and psychological well-being, influencing how individuals think, feel, and behave. It encompasses the ability to manage stress, maintain relationships, and make sound decisions, crucial for overall health and life satisfaction.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0vevcvv5': {
      'en': ' Awareness on Mental Health',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bnchlwpa': {
      'en':
          'Awareness on mental health involves understanding and recognizing the importance of emotional well-being. It encourages open conversations, reduces stigma, and promotes empathy towards those facing mental health challenges. Increasing awareness also fosters a supportive environment for seeking help and implementing preventive measures.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zh7j51tn': {
      'en': 'What is Anxiety?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hxk3v2ay': {
      'en':
          'Anxiety is a natural and adaptive response to stress or perceived threats, but when it becomes excessive or chronic, it can develop into a mental health disorder. It is characterized by persistent worry, fear, and physical symptoms like restlessness or trembling, impacting a person\'s daily life and functioning. Treatment often involves therapy, medication, or a combination of both.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ti21my77': {
      'en': 'Stress Management ',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7ho44wx9': {
      'en':
          '\nStress management involves adopting techniques to cope with and reduce the impact of stress on mental and physical well-being. Strategies may include mindfulness, exercise, and effective time management, empowering individuals to navigate challenges and maintain a balanced and resilient lifestyle',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zvrpnwn4': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // quiz1
  {
    'p5wtvb37': {
      'en': 'Question 1/3',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6etvz98q': {
      'en': 'How is your mood?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pelwhpmc': {
      'en': 'On a scale of 1 - 3 how are you feeling today?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vn1i6tef': {
      'en': 'Next Question',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vsydvvcd': {
      'en': 'Daily Quiz',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vdpipd2a': {
      'en': 'quiz',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // quiz2
  {
    'gjhqn6bo': {
      'en': 'Question 2/3',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ahoqy7qv': {
      'en': 'How was your day?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2ekk6wcl': {
      'en': 'Did you experience anything out of the ordinary?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mf7ysdei': {
      'en': 'Incredible  😇',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yqjwtgfx': {
      'en': 'Great 😃',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3x5jeb55': {
      'en': 'Good 🙂',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fhk5mr6t': {
      'en': 'Okay 😕',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '22hr8xb4': {
      'en': 'Really Bad 😞',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tc52pl1b': {
      'en': 'Next Question',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'b3ov30k6': {
      'en': 'Daily Quiz',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4gl8ukl8': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // mydiary
  {
    'gb09i17c': {
      'en': 'Pen down your thought here....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'i02pojig': {
      'en': 'Option 1',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wdr2g3p9': {
      'en': 'Done',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k3x899wx': {
      'en': 'My  Diary',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gfhzarlk': {
      'en': 'Diary',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Dashboardmood3
  {
    '4h2ksa36': {
      'en': 'Welcome',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bekl9g9f': {
      'en': 'Your recent Mood is below.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yal1yonh': {
      'en': 'Sad',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '230whgkj': {
      'en': 'Not happy',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6wabanmm': {
      'en': 'Happy',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1t8x6ful': {
      'en': 'Last 30 Days review',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm3f18og1': {
      'en': 'Done',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kswfrjqb': {
      'en': 'Mood Tracker',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '45pgdvw0': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // musicandpodcasts
  {
    'zo4c015r': {
      'en': 'Overcome your stress with Music.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7o6ofcw7': {
      'en': 'What do you want to listen today? ',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'go1p5y4x': {
      'en': 'Meditation music for sleep.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5xlpy37w': {
      'en': 'Miracle Tones',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'odzrmi9e': {
      'en': '19,366',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nvl7s312': {
      'en': '90h 30min',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kuq83j6b': {
      'en': 'KK Super Hit Songs All.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2si3re73': {
      'en': 'Krishnakumar Kunnath',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xlljhosk': {
      'en': '44,716',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '97no9vn3': {
      'en': '20h 27min',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fmil075r': {
      'en': 'Sad Hindi Songs.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6opc0c0m': {
      'en': 'Hitanshi',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9qtkqxwq': {
      'en': '186,389',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xcprfkmo': {
      'en': '19h 51min',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'atl6e2pj': {
      'en': 'Nature vibes.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zysfa9jo': {
      'en': 'Aesthectic vides',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm66d48ui': {
      'en': '24,722',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'atefil9a': {
      'en': '9h 22min',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fck9gt88': {
      'en': 'Recently Played',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yxbxajwv': {
      'en': 'For You',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7gxwh39x': {
      'en': 'All',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dn286cug': {
      'en': 'Music ',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2i3vze6h': {
      'en': 'Podcasts',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1ewd0wk7': {
      'en': 'Recently Played',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'og0zonp0': {
      'en': 'View more...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mcw886np': {
      'en': 'Music',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'sql0sddf': {
      'en': 'Music',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // DoctorRohitDeshmusk
  {
    'xb7p6cik': {
      'en': 'Psychiatris',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j23mat4w': {
      'en': 'Dr. Rohit P Deshmukh',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'km3i1897': {
      'en':
          'Kls Memorial Hospital, Navpada, Irla, Vile Parle West, Mumbai, Maharashtra',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iyukz0uj': {
      'en': 'Chat',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '41j3to3g': {
      'en': 'Call',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fjdjn5a4': {
      'en': 'Doctor Bio',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'umwwj226': {
      'en':
          '\"👨‍⚕️👨‍⚕️A comprehensive Psychiatry clinic.🏥🏥🏥 Dr. Rohit is one of the experienced psychiatrist serving in western suburban region of Mumbai. He has done his MD in Psychiatry from Mumbai\'s oldest and prestigious Grant Govt. Medical College & Sir JJ Group Of Hospitals Mumbai. He is well trained in adult psychiatry, child & adolescent psychiatry, women mental health, learning disorders, cognitive behavior therapy(CBT), MET & Brief intervention etc. He is well known for his soft spoken nature and patient oriented approach. It is one of the finest holistic mental health & psychiatry center. A perfect center for counselling and therapy.\"',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'unn2p1l7': {
      'en': 'Book Appointment',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jdv304zp': {
      'en': 'Favorite Doctor',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yy8ath0z': {
      'en': 'Details',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qn97tjck': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // nearbydoctor
  {
    'l1tei062': {
      'en': 'Mumbai - Maharashtra',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9mz3zp6y': {
      'en': '  Discussion Form.....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'u4ijn9or': {
      'en': 'Community',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k4h7f17y': {
      'en': 'Best Psychiatrist near me....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gty5eguu': {
      'en': 'Dr. Rohit P Deshmukh',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6smxacpa': {
      'en': '4.9 Stars',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4ptvxg23': {
      'en': 'View Now',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9vwn0i5k': {
      'en': 'DR. SANIL SINHASAN',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1gcmutjt': {
      'en': '5 Stars',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'eqdmqwt8': {
      'en': 'View Now',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0m1xwo10': {
      'en': 'Dr Sagar Mundada',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vyaheey7': {
      'en': '4.9 Stars',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gapqd3v9': {
      'en': 'View Now',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9njhpn5i': {
      'en': 'Dr. Naazneen',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nupyea1u': {
      'en': '4.4 Stars',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tnm1tmay': {
      'en': 'View Now',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'oebeuyd4': {
      'en': 'View More...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0u6hpkas': {
      'en': 'Some seminars on Mental Health...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'z0zgnoo3': {
      'en': 'Vikram Patel',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nfjcy0jo': {
      'en':
          'Nearly 450 million people are affected by mental illness worldwide. In wealthy nations, just half receive appropriate care, but in developing countries, close to 90 percent go untreated because psychiatrists are in such short supply. Vikram Patel outlines a highly promising approach -- training members of communities to give mental health interventions, empowering ordinary people to care for others.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'q4kenl8n': {
      'en': 'Introduction to Mental Health Awareness',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5a7rtdxx': {
      'en':
          'Raising mental health awareness can help you to understand your symptoms, find professional treatment, and, perhaps most importantly, break the mental health stigma that leaves so many people suffering in secret.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bisjhswm': {
      'en': 'Mental Health Awareness Webinar',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lk8f8u53': {
      'en':
          'Cleanse your mental & emotional health and accomplish your New Year Resolutions with the right practices at hand',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3t3yts4r': {
      'en': 'Doctors Near me',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7potdap0': {
      'en': 'Doctors near me',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // doctorappoiment
  {
    'b8wy90xj': {
      'en': 'Payment Detail',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rs97lz5r': {
      'en': 'Amount',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iq9pvqw0': {
      'en': '₹1800/-',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g92dpdbe': {
      'en': 'Vendor',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'osxg7mna': {
      'en': 'Doctors Appointment',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0f4yihg4': {
      'en': 'When',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'z440lmsv': {
      'en': 'Jul 26, 10:00am',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gw55x1me': {
      'en': 'Jul 26, 10:00am',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'saaymvok': {
      'en': 'Reason',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '914u57u2': {
      'en': 'There is a reason here for everything.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'neoyqjpe': {
      'en': 'Spent by',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4kng4m0z': {
      'en': '[display_name]',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g556r7uy': {
      'en': 'user.name@domainname.com',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'al1tk8u1': {
      'en': 'Done',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g5a0qwvy': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // doctorSanil
  {
    'j8ad1c95': {
      'en': 'Psychiatris',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g89kutuo': {
      'en': 'DR. SANIL SINHASAN',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nygoauvs': {
      'en':
          ' Mind Care Clinic, Zenith Medical Centre, A-402, Swami Gyan Jivandas Marg, Dadar West, Shivaji Park, Mumbai, Maharashtra',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0djaos6y': {
      'en': 'Chat',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'n3s5x8j3': {
      'en': 'Call',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1zy6ya41': {
      'en': 'Doctor Bio',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ralglg3v': {
      'en':
          '\"MBBS, MD Psychiatry, Consultant Psychiatrist & Sexologist Dr. Sanil Sinhasan is a renowned Psychiatrist & Sexologist practicing in Mumbai. He has an experience of more than 10 years in the treatment of various mental & sexual health disorders. He completed MBBS and did MD degree in Psychiatry from the prestigious TNMC & Nair Hospital, Mumbai. He gathered extensive knowledge and vast experience while working with government hospital and various private hospitals and psychiatric rehabilitation centres. Dr. Sanil is also actively involved in reducing stigma around mental illness by lectures, workshops and conducting awareness programs.\"',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xp03k9kd': {
      'en': 'Book Appointment',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gzrv7gtt': {
      'en': 'Favorite Doctor',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'spp1d08a': {
      'en': 'Details',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'a4mq9ngy': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // doctorappoiment2
  {
    'u8o34wrx': {
      'en': 'Payment Detail',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kd6meyza': {
      'en': 'Amount',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dt11knfp': {
      'en': '₹1200/-',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9g7iq77p': {
      'en': 'Vendor',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7ob2olxm': {
      'en': 'Doctors Appointment',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '28qz2an7': {
      'en': 'When',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vhgofrh2': {
      'en': 'Jul 26, 10:00am',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qctuys41': {
      'en': 'Jul 26, 10:00am',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gu42oqtn': {
      'en': 'Reason',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'c8f7oc00': {
      'en': 'There is a reason here for everything.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'w4lbstwn': {
      'en': 'Spent by',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'f8dxhrqt': {
      'en': '[display_name]',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lo8x3s1c': {
      'en': 'user.name@domainname.com',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cuk8tfrk': {
      'en': 'Done',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xdoywvbm': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // doctorSagar
  {
    'dmo86ke4': {
      'en': 'Psychiatris',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1y67y3eu': {
      'en': 'Dr Sagar Mundada',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'n6lmi9un': {
      'en':
          ' Healthsprings Ghatkopar, skye enclave,ground floor Dr MP road, MP Vaidya Marg, Ghatkopar, Ghatkopar East, Mumbai, Maharashtra ',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '72qod2v4': {
      'en': 'Chat',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rbh9cco0': {
      'en': 'Call',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ybx64ntf': {
      'en': 'Doctor Bio',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jxzz3o18': {
      'en':
          'Dr Sagar mundada has completed his MBBS and MD Psychiatry from one of India\'s top hospitals - JJ group of hospitals in mumbai .. He has provided expert Psychiatry service in KEM hospital also. He is consulting psychiatrist , de-addiction specialist, Motivation ,sales psychology coach and emotional wellness trainer and Corporate Trainer in Mumbai and online pan India.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8bk5ti9y': {
      'en': 'Book Appointment',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fqno91pv': {
      'en': 'Favorite Doctor',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1dp0n15y': {
      'en': 'Details',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm7mwxpmm': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // doctorNaazneen
  {
    'bclvmr3y': {
      'en': 'Primary Physician',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bu0fqeea': {
      'en': 'Dr. Naazneen',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'c5mqcngm': {
      'en':
          '1st Floor, Maina Gul Building, Ceasar Rd, opposite Citizens Bank, Dhakoji Sethpada, Navneeth Colony, Andheri West, Mumbai, Maharashtra',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nbawrx9x': {
      'en': 'Chat',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yzsx9mse': {
      'en': 'Call',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1fdxjzdf': {
      'en': 'Doctor Bio',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'exoywolj': {
      'en':
          '\"Dr Naazneen Ladak Syed has done her MBBS, DPM from India and MS Psychiatry and MSPAC from the USA. She has practised in the US for over 10 years and brings along the rich experience and exposure of having worked there. She has efficiently treated depression,bipolar, OCD , schizophrenia , anxiety cases effectively she also has a rich knowledge in dementia and geriatric psychiatry\"',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j43gpdue': {
      'en': 'Book Appointment',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hsovonp8': {
      'en': 'Favorite Doctor',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3ji6urm4': {
      'en': 'Details',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mxvmnov2': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // moredoctors
  {
    'bfkvg5v0': {
      'en': 'Nearby doctors are given below',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4lbmkc0q': {
      'en': 'Dr. Rohit Deshmukh',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'raulkreq': {
      'en': 'Psychiatrist , Psychotherapist, cousellor : Vile Parle',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cq1qs97w': {
      'en': 'Rs 500/-',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xqwaz0kl': {
      'en': 'Dr. Ketan Parmar',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6cnov48j': {
      'en':
          'MBBS, DPM (Psychiatry), MD - Psychological Medicine\nPsychiatrist,Sexologist,Addiction Psychiatrist,Psychiatrist,Neuropsychiatrist\n35 Years Experience Overall  (33 years as specialist)\n',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rdqz7fsv': {
      'en': 'Rs 500/-',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2x2m06ze': {
      'en': 'Dr. Anshu Kulkarni',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'exmr0k0k': {
      'en':
          'MD - Psychological Medicine, MBBS\nPsychiatrist\n25 Years Experience Overall  (22 years as specialist)\n21 Years Experience Overall',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'z0kjcmwl': {
      'en': 'Rs 600/-',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ictrtbqm': {
      'en': 'Dr. Chinmay Kulkarni',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yexcqh7r': {
      'en':
          'DPM (Psychiatry), MBBS\nPsychiatrist\n14 Years Experience Overall  (6 years as specialist)',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4k3n4bcv': {
      'en': 'Rs 500/-',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'navhjei9': {
      'en': 'Dr. Adita Agrawal',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xsq7qzox': {
      'en':
          'MBBS, DNB - Psychiatry\nPsychiatrist,Addiction Psychiatrist\n14 Years Experience Overall  (10 years as specialist)\n',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0r11ujbu': {
      'en': 'Rs 650/-',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'q26y9jhn': {
      'en': 'Dr. Sagar Mundada',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm1eucvzf': {
      'en':
          'M.D. (Psychiatry), MBBS\nPsychiatrist,Sexologist,Addiction Psychiatrist\n12 Years Experience Overall  (7 years as specialist)',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4asvsgsh': {
      'en': 'Rs 500/-',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fieda70x': {
      'en': '\nDr. Darpan Kaur',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4rbyfsaz': {
      'en':
          'MBBS, DNB - Psychiatry\nPsychiatrist,Neuropsychiatrist\n18 Years Experience Overall  (12 years as specialist)',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lb1tvx5z': {
      'en': 'Rs 600/-',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fbimw44g': {
      'en': 'Nearby Doctors',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g5yguxij': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // communitydisscuission
  {
    'hj6kvzju': {
      'en': 'Search discussions...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '295tghyz': {
      'en': 'Why is mental health important at you as you age?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'q4t3sw4r': {
      'en': '12 answers',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cgbkmyv5': {
      'en':
          'Maintaining mental health in older age is crucial for overall well-being, helping individuals cope with life transitions, sustain social connections, preserve cognitive function, and prevent mental health disorders. Good mental health supports resilience, contributes to a higher quality of life, and ensures effective coping with the challenges that come with aging',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'e8b0zykl': {
      'en': 'Posted by: John Doe',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bqzfpj7m': {
      'en': '2 hours ago',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'w4h6bf98': {
      'en': '24 likes',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iaflld0r': {
      'en': '8 comments',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fqjgvwhf': {
      'en': 'How does social media impact mental health?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cozgocis': {
      'en': '8 answers',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '77y95xan': {
      'en':
          'Social media can influence mental health both positively and negatively. Excessive use may contribute to feelings of inadequacy, loneliness, or anxiety, while positive interactions can provide support.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rfq8b3tj': {
      'en': 'Posted by: Jane Smith',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xv2yml2c': {
      'en': '1 day ago',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zdyfgzub': {
      'en': '16 likes',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '25px972s': {
      'en': '4 comments',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '33amze1t': {
      'en': 'How can one manage stress effectively?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ha270fye': {
      'en': '5 answers',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wblralqw': {
      'en':
          'Effective stress management involves strategies like regular exercise, deep breathing, mindfulness, time management, and seeking social support.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9btqygmj': {
      'en': 'Posted by: Sarah Johnson',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'llw33s76': {
      'en': '3 days ago',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dnnjpmgp': {
      'en': '8 likes',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1brv93bd': {
      'en': '2 comments',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v9eujj5a': {
      'en': 'Type here.....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6l5nixnp': {
      'en': 'Community Discussions',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // profile
  {
    'dn5bepve': {
      'en': 'Daksh Nayak',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iu21w8sh': {
      'en': 'DakshNayak72@gmail.com',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mxvo0o25': {
      'en': 'Emergency call',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vt3llez7': {
      'en': ' Notifications',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cf5fpkjb': {
      'en': 'About',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4bhtkpxe': {
      'en': 'Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yuw0xza1': {
      'en': 'Phone Number',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jfdjg950': {
      'en': 'Add Number',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5jc5h7p6': {
      'en': 'Language',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ulzk71at': {
      'en': 'English (eng)',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'n96zcjxd': {
      'en': 'Profile Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'olpzfawy': {
      'en': 'Edit Profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uyw47wkk': {
      'en': 'Notification Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jkb8nu6w': {
      'en': 'Log out of account',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'n5l7q5mn': {
      'en': 'Log Out?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '44t5jrft': {
      'en': 'profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // logout
  {
    'vzqtxmno': {
      'en': 'Are you sure you want to logout?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'c5xm7m7n': {
      'en': 'Yes',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fee5audx': {
      'en': 'No',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Drowback
  {
    'hmlv0fr1': {
      'en': 'Popular Games for Stress relief...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ia5y1g82': {
      'en': 'Jigsaw puzzle',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5iwmi6cv': {
      'en':
          'A jigsaw puzzle is a game where players assemble a picture from small, uniquely shaped pieces. It challenges spatial reasoning and patience, providing a satisfying and popular form of entertainment for all ages.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uzvftju9': {
      'en': 'PLAY NOW',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8z1tf8bw': {
      'en': 'Gems Swap',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'epa1wpdw': {
      'en':
          'Gems Swap is a match-three puzzle game where players swap adjacent gems to create matches and clear the board. The goal is to strategically align gems, triggering their disappearance and earning points within a set number of moves.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bjtztyn5': {
      'en': 'PLAY NOW',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'w03bi78a': {
      'en': 'Bubble Pop',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rpwuwg2s': {
      'en':
          'Bubble Pop is an arcade game where players match and pop groups of colored bubbles. The goal is to clear the screen with limited shots, making it a fun and engaging challenge.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3itr1bk4': {
      'en': 'PLAY NOW',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qi76sl3x': {
      'en': 'Virtual piano',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7413m775': {
      'en':
          'Virtual Piano is an online platform that enables users to play a digital piano using their computer keyboard or mouse. It serves as a user-friendly tool for musical exploration, allowing individuals to experiment with piano notes and melodies in a virtual setting, fostering creativity and learning',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'keukvu8p': {
      'en': 'PLAY NOW',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'x4l7lu4e': {
      'en': 'Bubble Shooter',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '12dov9oc': {
      'en':
          'Bubble Shooter is a classic puzzle game where players shoot colored bubbles to match and eliminate them. The goal is to clear the screen by strategically popping bubbles, creating an enjoyable and challenging gaming experience.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'md1m4no4': {
      'en': 'PLAY NOW',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qkss8a35': {
      'en': 'Pop it',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cgoyzsqn': {
      'en':
          'Pop it is a sensory fidget toy turned into a game where players press and pop virtual bubbles on a digital sheet. The aim is to relieve stress and boredom through the satisfying act of popping, offering a simple yet addictive form of relaxation',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nzctk6vj': {
      'en': 'PLAY NOW',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rc5x4zjo': {
      'en': 'View more...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm46q7a18': {
      'en': 'Games',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1cyn9cna': {
      'en': 'games',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // ARTICALS
  {
    'c64iaiof': {
      'en': 'Search Articals and News here....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vfhv9pun': {
      'en': 'Articals',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iqzec715': {
      'en': 'Mental Health and Suicide Prevention',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wfcajwoi': {
      'en': 'View more...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vqt8ti03': {
      'en': 'Don\'t Say It\'s Selfish: Suicide Is Not a Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v9bm5ajq': {
      'en': 'View more....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'i40mswb4': {
      'en':
          '4 ways parents can protect their mental well-being during a crisis',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4ejt7k1c': {
      'en': 'View more....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mcj6c73l': {
      'en': 'What kind of mental support do teenager wanr?',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pfnsenqe': {
      'en': 'View more....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0ec5k05e': {
      'en': 'News',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7311em58': {
      'en': 'Anxiety, depression high among children, says study',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '27fgl0xs': {
      'en': 'read more...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tn7nwa51': {
      'en': 'IIT Madras to map student behaviour to prevent depression',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1swqf066': {
      'en': 'read more...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'f1hen322': {
      'en': 'How social media affects students',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'b5vi2v3g': {
      'en': 'read more...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ji5nmuvw': {
      'en': 'In Telangana, student suicides 3 times higher than farmers',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '43toj79n': {
      'en': 'read more...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k95kk3me': {
      'en': 'Articals',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // CreateTask_new
  {
    'cow1ofmf': {
      'en': 'Add Task',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'sqs6i206': {
      'en': 'Fill out the details below to add a new task.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6g1krs69': {
      'en': 'Task Name',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lsjkh01z': {
      'en': 'Enter your task here....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zahnss47': {
      'en': 'Details',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jqf5xqyl': {
      'en': 'Enter a description here...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'njmp2mii': {
      'en': 'Cancel',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v586qeqn': {
      'en': 'Create Task',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // CreateTask_Edit
  {
    'csemlwz1': {
      'en': 'Add Task',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9gpgly27': {
      'en': 'Fill out the details below to add a new task.',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ak6t06m5': {
      'en': 'Task Name',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'sm78xigu': {
      'en': 'Enter your task here....',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8by7evue': {
      'en': 'Details',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2zstk9jr': {
      'en': 'Enter a description here...',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v72chvs1': {
      'en': 'Current Due Date',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4s9027iy': {
      'en': 'Cancel',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fuejtv6w': {
      'en': 'Update Task',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Miscellaneous
  {
    'tapjdv7x': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vn0egikg': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mbqi3hb9': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3hy0zt27': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ss2cza2e': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'okvx6701': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5cibk3o0': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v6el5ix3': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lnq4soi8': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gvyba6rq': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4rcac8km': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pfwr0xd7': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'f3gxeniw': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xhvjmfw4': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g0rdzoq4': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'f176hi5f': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nsiaaurt': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'u3cxrjcz': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xbzy246q': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vdnkhhhm': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ij3rk6k4': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9k1btse3': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vwqpp4i7': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qs0mlx9w': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'kn': '',
      'ml': '',
      'mr': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
].reduce((a, b) => a..addAll(b));
